apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-stats-service-config
  labels:
    app: {{ .Release.Name }}-stats-service
data:
{{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
