{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-stats-service-secret
  labels:
    app: {{ .Release.Name }}-stats-service
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
{{- end }}
{{- end }}
