apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stats-service
  labels:
    app: {{ .Release.Name }}-stats-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-stats-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
