{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tasks-service-secret
  labels:
    app: {{ .Release.Name }}-tasks-service
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
{{- end }}
{{- end }}
